spring:
  application:
    name: veritest

server:
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
  port: ${PORT:8080}
  tomcat:
    connection-timeout: -1

isabelle:
#  location: /root/Isabelle/bin/isabelle # For Docker
  location: /mnt/c/Programming/Thesis/Isabelle2023/bin/isabelle
  theories:
    include:
      - Canonicalizations.AbsPhase
      - Canonicalizations.AddPhase
      - Canonicalizations.AndPhase
      - Canonicalizations.BinaryNode
      - Canonicalizations.ConditionalPhase
      - Canonicalizations.MulPhase
      - Canonicalizations.NewAnd
      - Canonicalizations.NotPhase
      - Canonicalizations.OrPhase
      - Canonicalizations.ShiftPhase
      - Canonicalizations.SignedDivPhase
      - Canonicalizations.SignedRemPhase
      - Canonicalizations.SubPhase
      - Canonicalizations.XorPhase
  server:
    name: isabelle
    port: 8081
    password: ""
  session:
    session: Canonicalizations
    options:
      - document=false
      - show_question_marks=false
      - quick_and_dirty
    dirs:
      - /mnt/c/Programming/Thesis/veriopt-dev/isabelle
#      - /root/source # For Docker
    include_sessions:
      - OptimizationDSL
    verbose: true
  rate-limit:
    token: 1
    period: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.veriopt: debug