[tool.poetry]
name = "failedlogs"
version = "0.1.0"
description = ""
authors = ["Achmad Afriza Wibawa <achmad.afriza@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"